spring:
  jpa:
    generate-ddl: 'false'
    database: mysql
    defer-datasource-initialization: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  thymeleaf:
    cache: false
  datasource:
    password: '@project0303'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'developer'
    url: 'jdbc:mysql://49.50.167.124:3306/club-page?useSSL=false'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    livereload:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: '7d1b399f667856c2943a67723dd583f0'
            client-name: 'Kakao'
            redirect-uri: 'http://localhost:8080/api/user/login'
            scope: profile_nickname, account_email
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

custom:
  path:
    upload-tag: '/resource/icon'
